feat(docs): generate documentation with jsonschema2md

diff --git a/Makefile.toml b/Makefile.toml
--- a/Makefile.toml
+++ b/Makefile.toml
@@ -94,5 +94,23 @@ script = '''
 cosmwasm-check ./target/wasm32-unknown-unknown/release/*.wasm
 '''
 
+[tasks.generate_docs]
+dependencies = ["schema"]
+script = '''
+DOCS_FOLDER=docs
+echo "🔎 Checking jsonschema2md installed..."
+if ! command -v jsonschema2md &> /dev/null
+then
+    echo "\n❌   jsonschema2md could not be found"
+    echo "  Consider installing jsonschema2md to generate documentation.\n"
+    echo "＞ \`npm install -g @adobe/jsonschema2md\`\n\n"
+    exit
+fi
+
+echo "📚 Generating documentation..."
+jsonschema2md -d schema -o $DOCS_FOLDER --schema-extension json --schema-out $DOCS_FOLDER/schema
+echo "📖 Documentation has been successfully generated and available at $(pwd)/$DOCS_FOLDER/README.md"
+'''
+
 [config]
 default_to_workspace = false
