ci: add size limit github action

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -43,3 +43,35 @@ jobs:
 
       - name: Build wasm
         run: cargo make wasm
+
+      - name: Prepare size limit
+        run: |
+          cat << EOF > package.json
+          {
+            "name": "contracts",
+            "version": "1.0.0",
+            "description": "[![version](https://img.shields.io/github/v/release/okp4/contracts?style=for-the-badge)](https://github.com/okp4/contracts/releases) [![build](https://img.shields.io/github/workflow/status/okp4/contracts/Build?label=build&style=for-the-badge)](https://github.com/okp4/contracts/actions/workflows/build.yml) [![lint](https://img.shields.io/github/workflow/status/okp4/contracts/Lint?label=lint&style=for-the-badge)](https://github.com/okp4/contracts/actions/workflows/lint.yml) [![test](https://img.shields.io/github/workflow/status/okp4/contracts/Test?label=test&style=for-the-badge)](https://github.com/okp4/contracts/actions/workflows/test.yml) [![conventional commits](https://img.shields.io/badge/Conventional%20Commits-1.0.0-yellow.svg?style=for-the-badge)](https://conventionalcommits.org) [![License](https://img.shields.io/badge/License-BSD_3--Clause-blue.svg?style=for-the-badge)](https://opensource.org/licenses/BSD-3-Clause)",
+            "main": "index.js",
+            "scripts": {
+              "build": "cargo make wasm",
+              "test": "echo \"Error: no test specified\" && exit 1"
+            },
+            "repository": {
+              "type": "git",
+              "url": "git+https://github.com/okp4/contracts.git"
+            },
+            "author": "",
+            "bugs": {
+              "url": "https://github.com/okp4/contracts/issues"
+            },
+            "homepage": "https://github.com/okp4/contracts#readme",
+            "devDependencies": {
+              "@size-limit/preset-app": "^7.0.8"
+            }
+          }  
+          EOF
+
+      - name: Report wasm size limit
+        uses: andresz1/size-limit-action@v1
+        with:
+          github_token: ${{ secrets.GITHUB_TOKEN }}
